### ISSUE TITLE
Consolidar e resumir em um único README.md

### ISSUE THREAD

**Issue by neijobson** [spbgovbr/mod-sei-estatisticas#11]
É necessário resumir e consolidar as orientações em um único README.md.
- Já submeti um Pull Request.
- Verificar se o padrão da chave MdEstatisticas pode ficar da forma que coloquei com as chaves opcionais vazias ou a outra com valor false

**Comment by marlinhares** [comment]
Opa. Ficou melhor mesmo o README dessa forma.
Fiz alguns testes e funcionaram corretamente os parâmetros na forma sugerida.
Já fizemos o merge.

Em tempo, já pedimos para o pessoal tirar esse antigo.processoeletronico.gov.br e apontar para o painel novo. Porém ainda não foi aprovado.
O painel novo seria esse: https://paineis.processoeletronico.gov.br/painelnegociais
