### ISSUE TITLE
Retirar limite de tempo no script de verificação

### ISSUE THREAD

**Issue by marlinhares** [spbgovbr/mod-sei-estatisticas#12]
ini_set('max_execution_time', 0);

**Comment by rjunior069** [comment]
Precisando de um help, mesmo com todos os parametros setados para  a script de execução nao conclui, alguem tem alguma orientação?
'filesystemdu' => true,
                  'ignorarLeituraAnexos'=> true,
                  'tamanhoFs' => '197*********'

OBS: ja tirei valor do espaço em uso e coloquei valor total, ainda sim script não conclui a verificação.
sei 3.1.5
modulo 1.2.0

**Comment by marlinhares** [comment]
Olá @rjunior069  teria que verificar diretamente na sua tela pra tentar achar o problema.

Caso ainda esteja com problema:
- abra uma outra issue, pois essa aqui é para mapear a inclusao do execution_time, que eu posso tentar te ajudar, vou precisar de visualizar a sua tela online ou
- abra um chamado em https://portaldeservicos.economia.gov.br/ que o pessoal vai entrar em contato pra orientação.


Essa issue será fechada pois trata-se de outro assunto
