### ISSUE TITLE
Primeira execução timout devido à quantidade de dados

### ISSUE THREAD

**Issue by evertramos** [spbgovbr/mod-sei-estatisticas#6]
Prezados colegas, bom dia!

Estamos implantando o módulo estatístico, porém temos 500GB (arquivos) de dados para gerar estatísticas no primeiro envio... e está dando um erro de _Timout_. Acho que o script lê tanto os arquivos e a base que tb está bem grande aqui já...

1. Indicam alguma forma de conseguir enviar esse primeiro relatório para a api? Quebrando em partes ou subindo uma nova instancia específica pra isso, talvez?

2. Os demais envios são incrementais, correto?

**Comment by evertramos** [comment]
Segue erro de limite de memória ao testar o módulo:
![image](https://user-images.githubusercontent.com/905951/93608093-99e18a00-f9a0-11ea-888a-f0fd9bf626d2.png)

**Comment by marlinhares** [comment]
Opa desculpe a demora. Os arquivos anexos do SEI não devem ser contemplados ao gerar estatísticas.
Vc deve colocar o nome desse diretório na lista de ignorar_arquivos (maiores informaçoes de como configurar o ignorar_arquivos no README), dessa forma haverá um bypass desse dir na hora da leitura. O hash dos arquivos devem ser feitos apenas sobre o código fonte do sei, qualquer outro diretório que vc conheça deve ser adicionado ao array ignorar_arquivos.

Vou fechar a issue se achar necesário pode reabrir
