### ISSUE TITLE
Erro ao executar consulta pesada no SQL Server

### ISSUE THREAD

**Issue by josegfl** [spbgovbr/mod-sei-estatisticas#7]
Estávamos enfrentando erro ao executar a coleta do módulo e, após Debug, notamos que o erro estava em uma consulta que demorava alguns minutos para retornar resultado no SQL Server.

No arquivo MdEstatisticasColetarRN.php, adicionei a configuração ini_set('mssql.timeout', 60 * 10) para aumentar o timeout da consulta do SQLServer. 

O 10, na configuração acima, é a quantidade de minutos do timeout. Como a coleta está executando em menos de quatro minutos, creio que possa diminuir esse valor.

Nesse mesmo arquivo, na linha 545, a query foi atualizada para retornar os dados já tratados:

select distinct SUBSTRING(user_agent, CHARINDEX('(', user_agent),CHARINDEX(')', user_agent) - CHARINDEX('(', user_agent) + 1) as nome from infra_auditoria where user_agent is not null

Sugiro as mudanças acima para corrigir esse erro que possa surgir em outro órgão que use SQL Server.

**Comment by marlinhares** [comment]
Excelente @josegfl 
Temos aqui duas sugestões: uma para setar o timeout e outra para melhorar um dos selects

Com relação a segunda sugestão vamos precisar analisar melhor, pois as funções usadas devem ser compatíveis com a maioria dos SqlServers que o pessoal usa. Vou abrir uma issue separada para esse caso.

Com relação a primeira sugestão do ini_set('mssql.timeout', 60 * 10); vou gerar uma versão com a correção e fechar a issue quando tiver liberada na prox versão. Já fizemos o teste em outro orgão e funcionou fino.
